
package br.com.fiap.clientHeader;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AlunoWeb", targetNamespace = "http://ws.exemplos.fiap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlunoWeb {


    /**
     * 
     * @param password
     * @param parameters
     * @param username
     * @return
     *     returns br.com.fiap.clientHeader.InsertResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "insertResponse", targetNamespace = "http://ws.exemplos.fiap.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://ws.exemplos.fiap.com/AlunoWeb/insertRequest", output = "http://ws.exemplos.fiap.com/AlunoWeb/insertResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws.exemplos.fiap.com/AlunoWeb/insert/Fault/Exception")
    })
    public InsertResponse insert(
        @WebParam(name = "insert", targetNamespace = "http://ws.exemplos.fiap.com/", partName = "parameters")
        Insert parameters,
        @WebParam(name = "Username", targetNamespace = "http://ws.exemplos.fiap.com/", header = true, partName = "Username")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://ws.exemplos.fiap.com/", header = true, partName = "Password")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://ws.exemplos.fiap.com/", className = "br.com.fiap.clientHeader.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ws.exemplos.fiap.com/", className = "br.com.fiap.clientHeader.HelloResponse")
    @Action(input = "http://ws.exemplos.fiap.com/AlunoWeb/helloRequest", output = "http://ws.exemplos.fiap.com/AlunoWeb/helloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isAuthenticated", targetNamespace = "http://ws.exemplos.fiap.com/", className = "br.com.fiap.clientHeader.IsAuthenticated")
    @ResponseWrapper(localName = "isAuthenticatedResponse", targetNamespace = "http://ws.exemplos.fiap.com/", className = "br.com.fiap.clientHeader.IsAuthenticatedResponse")
    @Action(input = "http://ws.exemplos.fiap.com/AlunoWeb/isAuthenticatedRequest", output = "http://ws.exemplos.fiap.com/AlunoWeb/isAuthenticatedResponse")
    public boolean isAuthenticated();

    /**
     * 
     * @param password
     * @param parameters
     * @param username
     * @return
     *     returns br.com.fiap.clientHeader.ListAlunosResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "listAlunosResponse", targetNamespace = "http://ws.exemplos.fiap.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://ws.exemplos.fiap.com/AlunoWeb/listAlunosRequest", output = "http://ws.exemplos.fiap.com/AlunoWeb/listAlunosResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws.exemplos.fiap.com/AlunoWeb/listAlunos/Fault/Exception")
    })
    public ListAlunosResponse listAlunos(
        @WebParam(name = "listAlunos", targetNamespace = "http://ws.exemplos.fiap.com/", partName = "parameters")
        ListAlunos parameters,
        @WebParam(name = "Username", targetNamespace = "http://ws.exemplos.fiap.com/", header = true, partName = "Username")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://ws.exemplos.fiap.com/", header = true, partName = "Password")
        String password)
        throws Exception_Exception
    ;

}
