
package br.com.fiap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ArquivoService", targetNamespace = "http://exemplos.ws.fiap.com/", wsdlLocation = "http://l2901micro15:8080/Exemplo_06_WSArquivos/ArquivoService?wsdl")
public class ArquivoService
    extends Service
{

    private final static URL ARQUIVOSERVICE_WSDL_LOCATION;
    private final static WebServiceException ARQUIVOSERVICE_EXCEPTION;
    private final static QName ARQUIVOSERVICE_QNAME = new QName("http://exemplos.ws.fiap.com/", "ArquivoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://l2901micro15:8080/Exemplo_06_WSArquivos/ArquivoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ARQUIVOSERVICE_WSDL_LOCATION = url;
        ARQUIVOSERVICE_EXCEPTION = e;
    }

    public ArquivoService() {
        super(__getWsdlLocation(), ARQUIVOSERVICE_QNAME);
    }

    public ArquivoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ARQUIVOSERVICE_QNAME, features);
    }

    public ArquivoService(URL wsdlLocation) {
        super(wsdlLocation, ARQUIVOSERVICE_QNAME);
    }

    public ArquivoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ARQUIVOSERVICE_QNAME, features);
    }

    public ArquivoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArquivoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Arquivo
     */
    @WebEndpoint(name = "ArquivoPort")
    public Arquivo getArquivoPort() {
        return super.getPort(new QName("http://exemplos.ws.fiap.com/", "ArquivoPort"), Arquivo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Arquivo
     */
    @WebEndpoint(name = "ArquivoPort")
    public Arquivo getArquivoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://exemplos.ws.fiap.com/", "ArquivoPort"), Arquivo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ARQUIVOSERVICE_EXCEPTION!= null) {
            throw ARQUIVOSERVICE_EXCEPTION;
        }
        return ARQUIVOSERVICE_WSDL_LOCATION;
    }

}
