
package br.com.fiap.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AlunoWeb", targetNamespace = "http://ws.exemplos.fiap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlunoWeb {


    /**
     * 
     * @param aluno
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insert", targetNamespace = "http://ws.exemplos.fiap.com/", className = "br.com.fiap.client.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://ws.exemplos.fiap.com/", className = "br.com.fiap.client.InsertResponse")
    @Action(input = "http://ws.exemplos.fiap.com/AlunoWeb/insertRequest", output = "http://ws.exemplos.fiap.com/AlunoWeb/insertResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws.exemplos.fiap.com/AlunoWeb/insert/Fault/Exception")
    })
    public String insert(
        @WebParam(name = "aluno", targetNamespace = "")
        Aluno aluno)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://ws.exemplos.fiap.com/", className = "br.com.fiap.client.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ws.exemplos.fiap.com/", className = "br.com.fiap.client.HelloResponse")
    @Action(input = "http://ws.exemplos.fiap.com/AlunoWeb/helloRequest", output = "http://ws.exemplos.fiap.com/AlunoWeb/helloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isAuthenticated", targetNamespace = "http://ws.exemplos.fiap.com/", className = "br.com.fiap.client.IsAuthenticated")
    @ResponseWrapper(localName = "isAuthenticatedResponse", targetNamespace = "http://ws.exemplos.fiap.com/", className = "br.com.fiap.client.IsAuthenticatedResponse")
    @Action(input = "http://ws.exemplos.fiap.com/AlunoWeb/isAuthenticatedRequest", output = "http://ws.exemplos.fiap.com/AlunoWeb/isAuthenticatedResponse")
    public boolean isAuthenticated();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.fiap.client.Aluno>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAlunos", targetNamespace = "http://ws.exemplos.fiap.com/", className = "br.com.fiap.client.ListAlunos")
    @ResponseWrapper(localName = "listAlunosResponse", targetNamespace = "http://ws.exemplos.fiap.com/", className = "br.com.fiap.client.ListAlunosResponse")
    @Action(input = "http://ws.exemplos.fiap.com/AlunoWeb/listAlunosRequest", output = "http://ws.exemplos.fiap.com/AlunoWeb/listAlunosResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws.exemplos.fiap.com/AlunoWeb/listAlunos/Fault/Exception")
    })
    public List<Aluno> listAlunos()
        throws Exception_Exception
    ;

}
